// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: PermitService.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	IP       string `protobuf:"bytes,3,opt,name=IP,proto3" json:"IP,omitempty"`
}

func (x *PermitReq) Reset() {
	*x = PermitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PermitService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermitReq) ProtoMessage() {}

func (x *PermitReq) ProtoReflect() protoreflect.Message {
	mi := &file_PermitService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermitReq.ProtoReflect.Descriptor instead.
func (*PermitReq) Descriptor() ([]byte, []int) {
	return file_PermitService_proto_rawDescGZIP(), []int{0}
}

func (x *PermitReq) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *PermitReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PermitReq) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

type PermitResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Reason  string `protobuf:"bytes,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
}

func (x *PermitResult) Reset() {
	*x = PermitResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PermitService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermitResult) ProtoMessage() {}

func (x *PermitResult) ProtoReflect() protoreflect.Message {
	mi := &file_PermitService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermitResult.ProtoReflect.Descriptor instead.
func (*PermitResult) Descriptor() ([]byte, []int) {
	return file_PermitService_proto_rawDescGZIP(), []int{1}
}

func (x *PermitResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PermitResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RstIPReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IP string `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
}

func (x *RstIPReq) Reset() {
	*x = RstIPReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PermitService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RstIPReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RstIPReq) ProtoMessage() {}

func (x *RstIPReq) ProtoReflect() protoreflect.Message {
	mi := &file_PermitService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RstIPReq.ProtoReflect.Descriptor instead.
func (*RstIPReq) Descriptor() ([]byte, []int) {
	return file_PermitService_proto_rawDescGZIP(), []int{2}
}

func (x *RstIPReq) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

type RstLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login string `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
}

func (x *RstLoginReq) Reset() {
	*x = RstLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PermitService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RstLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RstLoginReq) ProtoMessage() {}

func (x *RstLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_PermitService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RstLoginReq.ProtoReflect.Descriptor instead.
func (*RstLoginReq) Descriptor() ([]byte, []int) {
	return file_PermitService_proto_rawDescGZIP(), []int{3}
}

func (x *RstLoginReq) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

var File_PermitService_proto protoreflect.FileDescriptor

var file_PermitService_proto_rawDesc = []byte{
	0x0a, 0x13, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x09, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x22, 0x40, 0x0a, 0x0c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x1a, 0x0a, 0x08, 0x52, 0x73, 0x74, 0x49,
	0x50, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x50, 0x22, 0x23, 0x0a, 0x0b, 0x52, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x32, 0xa9, 0x01, 0x0a, 0x06, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x74, 0x12, 0x31, 0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x49, 0x50, 0x12, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x73, 0x74, 0x49, 0x50, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0a, 0x52,
	0x65, 0x73, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PermitService_proto_rawDescOnce sync.Once
	file_PermitService_proto_rawDescData = file_PermitService_proto_rawDesc
)

func file_PermitService_proto_rawDescGZIP() []byte {
	file_PermitService_proto_rawDescOnce.Do(func() {
		file_PermitService_proto_rawDescData = protoimpl.X.CompressGZIP(file_PermitService_proto_rawDescData)
	})
	return file_PermitService_proto_rawDescData
}

var file_PermitService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_PermitService_proto_goTypes = []interface{}{
	(*PermitReq)(nil),     // 0: api.PermitReq
	(*PermitResult)(nil),  // 1: api.PermitResult
	(*RstIPReq)(nil),      // 2: api.RstIPReq
	(*RstLoginReq)(nil),   // 3: api.RstLoginReq
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_PermitService_proto_depIdxs = []int32{
	0, // 0: api.Permit.CheckQuery:input_type -> api.PermitReq
	2, // 1: api.Permit.ResetIP:input_type -> api.RstIPReq
	3, // 2: api.Permit.ResetLogin:input_type -> api.RstLoginReq
	1, // 3: api.Permit.CheckQuery:output_type -> api.PermitResult
	4, // 4: api.Permit.ResetIP:output_type -> google.protobuf.Empty
	4, // 5: api.Permit.ResetLogin:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PermitService_proto_init() }
func file_PermitService_proto_init() {
	if File_PermitService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PermitService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PermitService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermitResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PermitService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RstIPReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PermitService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RstLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PermitService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PermitService_proto_goTypes,
		DependencyIndexes: file_PermitService_proto_depIdxs,
		MessageInfos:      file_PermitService_proto_msgTypes,
	}.Build()
	File_PermitService_proto = out.File
	file_PermitService_proto_rawDesc = nil
	file_PermitService_proto_goTypes = nil
	file_PermitService_proto_depIdxs = nil
}
